# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  - name: DOCKER_IMAGE
    value: nikhilsinghdocker/testdotnet
  - name: DOCKER_TAG_RELEASE
    value: latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'nikhildocker'
          repository: $(DOCKER_IMAGE)
          tags: $(DOCKER_TAG_RELEASE)
          command: 'build'
          Dockerfile: '**/Dockerfile'
      - task: Docker@2
        inputs:
          containerRegistry: 'nikhildocker'
          repository: $(DOCKER_IMAGE)
          tags: $(DOCKER_TAG_RELEASE)
          command: 'push'
